execute_script:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: xenia_home
    script_id:
      example: 12
      selector:
        number:
          min: 1
          mode: box
    script_name:
      example: "My Script"
      selector:
        text:
